<?php
declare(strict_types = 1);

use yii\db\Migration;

class m150101_000000_init extends Migration
{
    public function up()
    {
        return parent::up(); // TODO: Change the autogenerated stub
    }

    public function down()
    {
        return parent::down(); // TODO: Change the autogenerated stub
    }
}