POST http://{{host}}/refresh-token

{
    "data" : {
        "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiIsImp0aSI6IjAwZWU0ODNhLTYwZjMtNDY0Yi04Y2UyLTBhMTYzNjUxMDU5MCJ9.eyJpc3MiOiJtdSIsImF1ZCI6ImxlYXJub2ZmIiwianRpIjoiMDBlZTQ4M2EtNjBmMy00NjRiLThjZTItMGExNjM2NTEwNTkwIiwiaWF0IjoxNTI4MTc4NjQ4LCJuYmYiOjE1MjgxODIyNDgsImV4cCI6MTUyOTM4ODI0OCwidXNlcklkIjoxOSwic2NvcGUiOltdfQ.SxahK9KkjyKepX9qc5FoPoo451CH2rIWz4IuxUSbxmHTHiK6ieRtatb4cehDNGLUxCULcLVU9QX9FyVUdpND4wIalN-nxC_xzpFf-3jD-wi9RC6iyMbxpkZql8EjnGKqjEbCQZbP5KwLDKElBtMhU-g3RQJ8Qa7nJm_fM-hsO6qQArrI_2rSbxJRrhXfVFH1pai2pgIfrB6x5-iOeBz64OAkHiA5vCu6E6ZT_t8HzKu-23Cq7lS02PR3TfAhhpvHSDrQbho8bwkuiL7s2i6uzJ-X4TQAkCCkW-hzKVu5Ow1jVRmkMtKWKhiYrUO1F9SihnEsLbercJHFFdZaKKsBc8iBpKT7N6kGzEsdFI44cwiNDCK8Ywt-ASJ6nD-COoShLAa9867cEWdt8hZECJ3vdDPzQM5s-dYBX1IDv9Zh6OIcYR2nLXWCJLdH8VD940TMoPgpud4QTimyoJFuHNAPqgEMxkPUbXqNMGknlxLX6er-ZkaUgbjsFk49CtfjZQMfKYfJ8Ei0pk8umZxjgydhPTq6KaLZZTL6q7thytIBGIFpneqMRkl5niHDjkedhye97cq2NxWVg1PogOysuIuMzf1ObdxmERLXg1oRpnsq_w5u-feDG4-dEeO-Lks_errFVVpN_a4jUVKDLNM3KhJl4OO9GHRqoz2Kia-RRY-gddY",
        "refreshToken": "450501b9-a61a-46ec-bb39-02ab647387da"
    }
}

###