POST http://{{host}}/verify-token
jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiIsImp0aSI6IjE3ZmQ2ZDIyLWMwODMtNGMwNS1iMmFiLTA5ZjBiYTUyNDQ4NyJ9.eyJpc3MiOiJtdSIsImF1ZCI6ImxlYXJub2ZmIiwianRpIjoiMTdmZDZkMjItYzA4My00YzA1LWIyYWItMDlmMGJhNTI0NDg3IiwiaWF0IjoxNTI3NzQ2MjgzLCJuYmYiOjE1Mjc3NDk4ODMsImV4cCI6MTUyODk1NTg4MywidXNlcklkIjoxOSwic2NvcGUiOltdfQ.bFy-9DmzwvG4L2XV6HlpjMR4pPwjWJKAsNqhdF0fiZYhVEgZ2iJLfVc-YBSNuvinUK_hm9PcTNlwFgdpSfiraBCHyZ9_xF021EKao3Vo9dPqb0ULjeVJaCXkFFOBznD7ETRxVySZ0E08559BK51o0GRLFP2izgXTMgX6Kb934rt8rUk4mk864rbBcEGaD8Y6KeugmfxJJftAlJqzuTigjvxOMnrt9QzOvMWvtNBN600AB0GvAiTTKgcaxYmu4BYQoDsv0r6jaUT9jKkTuCrX_WBNg9pKEwtM3_o4iZRDIc9xnJuzh7JmuDXmPVxPghSwer__UnxiIiyllEnr3Y8iBlg_Oj6Xbfxv9F8ppGosKQc2PFWuVh_Sd-WYd1c40p0Z7j7K8Tp1mxFvCFAroC6JvpXChIGX182i57sS2Gmhjegq8g8gfLEzEPHyMLrEiQXp_Fg2QkAnkwzxArJc-ylNXaMq1x61DxEFpJ5FEmPssh_0hVrJQlf5zPMLYvcQrY13S43XB-lIRI09W8wFkHIfqxkckTCVSMubo-6qhVcBzZnz29OV2jF-7AcbdoCYeYWF5cbxUUeooG-lNc1bfwpABzYg3lNBRkl9y3uNg5wLL3lp5eB1MRRf2ArxbwnU1XZb6Zssv4L88fJrZfMk61GRtxiKCrBE-hCTUnfl_LYuJV0

{
    "data" : {
        "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiIsImp0aSI6IjNhN2M2ODEyLWE4ZDctNDk2NC04YjMzLTcyNDlhZDA1ODc0OCJ9.eyJpc3MiOiJtdSIsImF1ZCI6ImxlYXJub2ZmIiwianRpIjoiM2E3YzY4MTItYThkNy00OTY0LThiMzMtNzI0OWFkMDU4NzQ4IiwiaWF0IjoxNTI4MTc2MzUwLCJuYmYiOjE1MjgxNzk5NTAsImV4cCI6MTUyOTM4NTk1MCwidXNlcklkIjoxOSwic2NvcGUiOltdfQ.R50Zoi7xrfNug2AWKK6r4xXVZlCwc5sX9XKcCBxqS9e8Kg1z63glbBP_-RgYpeFDbwv9pyItakuJt8_tI9jpEB5xWr7i96vd9867cjobJNy_TpYUfih9teT2clm6DMGSxGyTinw90h1keS-AMl1XERCgW5mk_dbHernumcbAVOfBwm7SSbQxaQnrqy_Go0Fijz3MoYW8aP7OTXXpugwl_1QPGsKvUP116iHH_IXkZ6J-2ZrEcqF-WPfdlgGw6uT_CvobU9hgIiD6DQDd2UZaGzxi0ixy59veXSFvZrK5289fgu2ruZJB-3fVRLJarYwOvkEU98J4f2TWZGlPEF-CpJr7p4iHPbu8P1W4f2Ckhid3vZFcGaH5sxBt3Zbn7InrR8YRzJp4rXlzAX8nP51kBxwnlQjTszdgz1oPRC_MdQNZVCARUBfJu6wNSQEtxZVGeeS_uSc4l335sLiqPwxq5CGjtp48hSM-fE5KRDjbrofDy4DfZOFHofaLEzeFe8kOj9afvim2aLsXVPIxuG4pqgckIX5zp9Ij2LDXMrx_RbpPZCQ_Skigvx8G1yDlcDxpewPbFsPkK2lkTbtw-0T_8j64RN74krUpeUVnI7_6k-7b-zmFivymykHouqhueYQvkxFlryouh9Eek8WaMDGnoMTLeTQhCRsVOE7C6ciuZa0"
    }
}

###