POST http://{{host}}/logout
jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiIsImp0aSI6IjE3ZmQ2ZDIyLWMwODMtNGMwNS1iMmFiLTA5ZjBiYTUyNDQ4NyJ9.eyJpc3MiOiJtdSIsImF1ZCI6ImxlYXJub2ZmIiwianRpIjoiMTdmZDZkMjItYzA4My00YzA1LWIyYWItMDlmMGJhNTI0NDg3IiwiaWF0IjoxNTI3NzQ2MjgzLCJuYmYiOjE1Mjc3NDk4ODMsImV4cCI6MTUyODk1NTg4MywidXNlcklkIjoxOSwic2NvcGUiOltdfQ.bFy-9DmzwvG4L2XV6HlpjMR4pPwjWJKAsNqhdF0fiZYhVEgZ2iJLfVc-YBSNuvinUK_hm9PcTNlwFgdpSfiraBCHyZ9_xF021EKao3Vo9dPqb0ULjeVJaCXkFFOBznD7ETRxVySZ0E08559BK51o0GRLFP2izgXTMgX6Kb934rt8rUk4mk864rbBcEGaD8Y6KeugmfxJJftAlJqzuTigjvxOMnrt9QzOvMWvtNBN600AB0GvAiTTKgcaxYmu4BYQoDsv0r6jaUT9jKkTuCrX_WBNg9pKEwtM3_o4iZRDIc9xnJuzh7JmuDXmPVxPghSwer__UnxiIiyllEnr3Y8iBlg_Oj6Xbfxv9F8ppGosKQc2PFWuVh_Sd-WYd1c40p0Z7j7K8Tp1mxFvCFAroC6JvpXChIGX182i57sS2Gmhjegq8g8gfLEzEPHyMLrEiQXp_Fg2QkAnkwzxArJc-ylNXaMq1x61DxEFpJ5FEmPssh_0hVrJQlf5zPMLYvcQrY13S43XB-lIRI09W8wFkHIfqxkckTCVSMubo-6qhVcBzZnz29OV2jF-7AcbdoCYeYWF5cbxUUeooG-lNc1bfwpABzYg3lNBRkl9y3uNg5wLL3lp5eB1MRRf2ArxbwnU1XZb6Zssv4L88fJrZfMk61GRtxiKCrBE-hCTUnfl_LYuJV0

{
    "data" : {
        "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiIsImp0aSI6ImI4MDhhMTkzLTZjNmEtNDhhYi1iZTVmLWI2MDg2YTFlZDIyZiJ9.eyJpc3MiOiJtdSIsImF1ZCI6ImxlYXJub2ZmIiwianRpIjoiYjgwOGExOTMtNmM2YS00OGFiLWJlNWYtYjYwODZhMWVkMjJmIiwiaWF0IjoxNTI4MDA0NDU4LCJuYmYiOjE1MjgwMDgwNTgsImV4cCI6MTUyOTIxNDA1OCwidXNlcklkIjoxOSwic2NvcGUiOltdfQ.gFqvG8VFxOPMcHwx5-oguzi0vJff4nisUyPEZsk0iZnrGd9MH_aEulw6edBvFFVP7HJyQXmif6KKfzXeuC7OVRJ8F1GWHByNgYGamFcMmh48LrgsUsBFoQr5fv7s6uxnrMPP-laGEz7K4sDBrn8HjQcT1rgp9LKt8Znyie9kNRSpc5j-y8KlSdQq85uGpjNOajpeLsbjm-3Qq_yBieTZjl7_uhS9DA6LStto8vLzIw4oPTzx-TPK7aPn3GFax2Zppv6IfkZBanY4Pr8aNge63w1eRHv1nKS1GLHEf_bUxCAYX5xsu7m-bn3U9NP1dA2_Mxl55kXLww9dlbo7R_FmL5VmBR6nJESySQinSIEUkCjiAoSeZL091FkrBGv-O1LYeXHOumszYwj-IBAchcPlxAtENK7j5GaPNxYnFeRF9fkbTw0GeYrImA-pG1tAIQfFoVc5r302K9gFvaeAodaafOUSoUvltdBc5WuE6Nh8i7GUwwJGcsRFF4zZfn3XLLHKgvM6w6zavA2P3tpMjda1VGfK5zRxA_Z9K10fEVgXhtRcIIub81wgeEl0jHJ1LgLtKSLz1AMA4jsVQNdlrZ8tf3TZjUNVXO4jerb8spbrNUwkg7F4na0cioyLFQriBZT_ONaNFUPHJWQ0DqEWDc3Rr_Pgv8MdIVrPF3oLKFIlp-o"
    }
}

###